### ISSUE TITLE
use preprocessor to map define'd constants/macros

### ISSUE THREAD

**Issue by timotheecour** [genotrance/nimterop#11]
as discussed here https://gitter.im/nimgen/Lobby?at=5bf638386621313894fbddac

## links
https://stackoverflow.com/questions/2224334/gcc-dump-preprocessor-defines

**Comment by genotrance** [comment]
I believe this is now implemented with -dD. We need to add tests though.

**Comment by c-blake** [comment]
This seems as appropriate an issue thread as any to chime in, but I saw that I think you (shashlick?) in IRC a few days ago asked about `cligen` handling `-I` multiple times or probably similarly for `-D`.  No one seemed to answer you, and I suppose there's a chance you tried it and saw that it "just worked", but its CL usage is a little subtle.

An explicit `=` or `:` or long option param separation causes things to "reset" to the argument.  So, `--defines=def0,def9` will clobber any existing seq with just `["def0", "def9"]`.  A short option (if you added `short={ "defines": 'D', "includeDirs", 'I' }` ) would let the CLI user say `-Ddef1 -Ddef2` with the intended accumulating meaning. They can also use an explicit append mode via `--defines+=def3` and even a prepend mode `-I^=earlierpath`.  I found it a little tricky balancing the "need to reset" with the principle of least surprise, and this is only really in the documentation for `argcvt`.  I could be convinced that maybe "reset and assign" should be spelled `.=` or something.  There's been talk of the need for a `--help-syntax` or something more to guide CL users.

If you hate this syntax, you can also override all of this default syntax by just by doing an `import cligen, cligen/argcvt` and, between that `import` and the `dispatch`.  defining your own version of `proc argParse*[T](dst: var seq[T], ...` .  It's only a 19 line proc in `cligen/argcvt.nim`, but you might also need to learn some more internals to do it.

**Comment by genotrance** [comment]
@c-blake - thanks for chiming in. I wasn't able to since the `+=` and `^=` syntax isn't obvious and there weren't any examples either. I also just tried to see the [argcvt](http://htmlpreview.github.io/?https://github.com/c-blake/cligen/blob/master/argcvt.html) docs and it doesn't seem to work. Says table not accessible.

That being said, @timotheecour has already migrated nimterop to use cligen. Here's the syntax so far:

```
Usage:
  main [required&optional-params]
  Options(opt-arg sep :|=|spc):
  -h, --help                                  write this help to stdout
  -m=, --mode=         string       "cpp"     language; see CompileMode
  -p, --past           bool         false     print AST output
  --pnim               bool         false     run preprocessor on header
  --pretty             bool         true      set pretty
  --preprocess         bool         false     print Nim output
  -d=, --defines=      ,SV[string]  EMPTY     definitions to pass to preprocessor
  -i=, --includeDirs=  ,SV[string]  EMPTY     include directory to pass to preprocessor
  -s=, --source=       string       REQUIRED  C/C++ source/header
```

**Comment by c-blake** [comment]
Not sure what's wrong with the `http://htmlpreview.github.io/?`, but I also get that error a day later.  That file is just the output of `nim doc argcvt.nim`.  So, you can also just read the doc comments there.

Also, I don't think I was so clear...Had you tried just `"-i dir1 -i dir2"` (with no `"="`) then it would have appended rather than doing a clobbering assignment.  It only does the clobbering assignment with an explicit `'='` (at least right now).  So, it seemed possible to me you might have discovered that subtle property by accident.  I don't think of `+=` as very likely to be tried.  But, yeah, there should be example usage/--help-syntax.  `parsopt3` is also quite a bit more flexible than the stdlib `parseopt`s.

**Comment by timotheecour** [comment]
> Not sure what's wrong with the http://htmlpreview.github.io/?, but I also get that error a day later.

not sure what you meant above but http://htmlpreview.github.io/?https://github.com/c-blake/cligen/blob/master/argcvt.html worked for me (link given at end of README in https://github.com/c-blake/cligen ; admittedly I'd prefer if that link appeared on top of README)

> `--help-syntax`

=> moved that discussion to https://github.com/c-blake/cligen/issues/64

**Comment by timotheecour** [comment]
@genotrance 
> I believe this is now implemented with -dD. We need to add tests though.

is it, though? that's why I was trying to test with https://github.com/genotrance/nimterop/pull/17 but it fails

**Comment by timotheecour** [comment]
indeed, travis now passes! windows still fails though

**Comment by genotrance** [comment]
This has been [fixed](https://github.com/genotrance/nimterop/commit/1e086d59595c24ee8ec3f1dcc02b55d97fe9e2ec).

**Comment by timotheecour** [comment]
@genotrance could we reopen?
`constants` works but not macros, see https://github.com/genotrance/nimterop/pull/30
