### ISSUE TITLE
SIGSEGV in toast

### ISSUE THREAD

**Issue by zevv** [genotrance/nimterop#39]
```
./toast -D=_FILE_OFFSET_BITS=64  -np /usr/include/fuse.h > fuse.nim
Traceback (most recent call last)
cligen.nim(797)          toast
cligen.nim(552)          dispatchmain
toast.nim(137)           main
toast.nim(103)           process
ast.nim(135)             printNim
ast.nim(117)             searchAst
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

```
Linux platdoos 4.19.0-1-amd64 #1 SMP Debian 4.19.13-1 (2018-12-30) x86_64 GNU/Linux

Distributor ID:	Debian
Description:	Debian GNU/Linux buster/sid
Release:	unstable
Codename:	sid

Nim Compiler Version 0.19.2 [Linux: amd64]
Compiled at 2019-01-17
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 7beea1642ddf7845a9a0034c7a93ccbe15894c36
active boot switches: -d:release
```

**Comment by genotrance** [comment]
I just tried with #head and it doesn't crash with libfuse head. Can you please try again?

**Comment by genotrance** [comment]
Nope, no luck. Can you attach your version of fuse.h and fuse_common.h?

**Comment by zevv** [comment]
Attached is my preprocessed fuse.h, crashes toast with

```
./toast -np /tmp/fuse.h.txt
```

Note that

```
./toast -p /tmp/fuse.h.txt
```

results in no output at all

[fuse.h.txt](https://github.com/genotrance/nimterop/files/2775341/fuse.h.txt)

**Comment by genotrance** [comment]
The file uploaded is already processed by the preprocessor so when you run it through again, it doesn't do anything. But now, toast has no way to know which lines from the output are relevant since you are now processing a fuse.h.txt at some different location than the `/usr/include/fuse.h` annotations in the file.

I can fix the crash such that when there's no preprocessor output, it will stop executing altogether and raise an error message.

**Comment by zevv** [comment]
Hm I see - but this still does not catch the root cause. I'm not able to isolate and send you my headers, since much more then just fuse gets pulled in. I'll try to dig in ninterop to see if I can understand what is causing the troubles.
