### ISSUE TITLE
Nim case insensitivity -> identifier clash

### ISSUE THREAD

**Issue by zevv** [genotrance/nimterop#42]
The following 2 definitions from SDL2 cause a clash in Nim namespace:

```
typedef enum
{
    ...
} SDL_GLContextResetNotification;
```

```
typedef enum
{
    ...
    SDL_GL_CONTEXT_RESET_NOTIFICATION,
    ....
} SDL_GLattr;
```

**Comment by genotrance** [comment]
@Araq - do you have any suggestions on how to differentiate these two? Here's the current output from nimterop:

```nim
type SDL_GLContextResetNotification* = distinct int
converter enumToInt(en: SDL_GLContextResetNotification): int {.used.} = en.int

type SDL_GLattr* = distinct int
converter enumToInt(en: SDL_GLattr): int {.used.} = en.int

const
  headerb = "b.h"
  abc* = 0.SDL_GLContextResetNotification
  SDL_GL_CONTEXT_RESET_NOTIFICATION* = 0.SDL_GLattr
```

**Comment by Araq** [comment]
the ``const`` is lowercase, the type Uppercase.

**Comment by timotheecour** [comment]
this would be 100% fixed by https://github.com/nim-lang/Nim/issues/8807

**Comment by genotrance** [comment]
The new plugin system will allow the user to rename these problematic symbols per their preference. There's no clear [solutions](https://github.com/nim-lang/Nim/issues/8807) from the Nim compiler itself but we can at least allow the user to handle this situation for now. Nimterop will aim to provide clear errors and guidance so that users can figure out such situations clearly.
